vtally_dashboard:
    path:     /
    defaults: { _controller: VtallyBundle:Default:dashboard }
    
vtally_notification:
    path:     /notification
    defaults: { _controller: VtallyBundle:Default:notification }

votes: 
  type: rest
  resource:     "VtallyBundle:Api"
  prefix:  api

vtally_importCSV:
    path:  /admin/import/file
    defaults: { _controller: VtallyBundle:Default:importCSV }
    
vtally_download_pinkSheet:
    path:  /download-pinkSheet
    defaults: { _controller: VtallyBundle:Default:zipAndDownload }
