vtally_pink_sheet:
    path:  /pink-sheet/{id}
    defaults: { _controller: VtallyBundle:Default:pinkSheet }
    

vtally_dashboard:
    path:     /
    defaults: { _controller: VtallyBundle:Default:dashboard }

vtally_constituencies_modal:
    path:     /constituencies-modal/{id}
    defaults: { _controller: PrBundle:Presidential:consituenciesPrModal }
    
vtally_polling_stations_modal:
    path:   /polling-stations-modal/{id}
    defaults: { _controller: PrBundle:Presidential:pollingStationsPrModal }
    
vtally_constituencies:
    path:     /constituencies
    defaults: { _controller: VtallyBundle:Default:constituency }
    
vtally_polling_stations:
    path:     /polling-stations
    defaults: { _controller: VtallyBundle:Default:pollingStation }
    
vtally_national:
    path:     /national
    defaults: { _controller: VtallyBundle:Default:national }
    
vtally_notification:
    path:     /notification
    defaults: { _controller: VtallyBundle:Default:notification }

votes: 
  type: rest
  resource:     "VtallyBundle:Api"
  prefix:  api

vtally_importCSV:
    path:  /admin/import/file
    defaults: { _controller: VtallyBundle:Default:importCSV }
    
vtally_download_pinkSheet:
    path:  /download-pinkSheet
    defaults: { _controller: VtallyBundle:Default:zipAndDownload }
